### PR TITLE
Fix small typo

### PR DESCRIPTION
**Pull request by toby**

### CODE REVIEW

**Comment by Arkaeriit** [comment]
Thank you for this fix.

**Comment by toby** [comment]
No worries! We also just posted about this on the official Charm twitter account:

https://twitter.com/charmcli/status/1478477879260459012

It's very cool!

**Comment by Arkaeriit** [comment]
Thank you very much for this. That is very nice of you.

**Comment by toby** [comment]
No worries, it's really cool. Also, we have a slack if you ever have any Soft Serve/Charm questions: https://charm.sh/slack

**Comment by Arkaeriit** [comment]
Thanks for the link. I will look into it when I need it.

**Pull request merged**
